name: veterinary_clinic_app
description: "Veterinary Clinic Appointments App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+7
  flutter_mobx: ^2.0.6+3
  flutter_modular: ^5.0.3
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/dog.png
    - assets/images/logo.png

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700